global:
  env:
    - TRASS=1
options:
  system:
    ubuntu:
      global:
        dist:     ubuntu
        release:  trusty
        arch:     amd64

        env:
          - DEBIAN_FRONTEND=noninteractive

        container:
          user:
            username: ubuntu
            home: /home/ubuntu
            prepare:
              - "echo 'ubuntu ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"
          prepare:
            - sudo echo 'APT::Get::Assume-Yes "true";'   >  /etc/apt/apt.conf.d/90forceyes
            - sudo echo 'APT::Get::force-yes "true";'    >> /etc/apt/apt.conf.d/90forceyes
            - sudo apt-get update
            - sudo apt-get install wget tar

      options:
        language:
          haskell:
            options:
              ghc:
                7.8:
                  container:
                    - wget https://www.haskell.org/platform/download/2014.2.0.0/haskell-platform-2014.2.0.0-unknown-linux-x86_64.tar.gz -O haskell-platform.tar.gz
                    - cd /
                    - sudo tar xvf ~/haskell-platform.tar.gz
                    - sudo /usr/local/haskell/ghc-7.8.3-x86-64/bin/activate-hs
                7.6:
                  container:
                    - sudo apt-get update
                    - sudo apt-get install haskell-platform=2013.2.0.0.debian3

